# (PART) Modules {-}

# Module 1

## Lecture


<!--<iframe width="640" height="360" src="YOUTUBE EMBED LINK" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>-->

### 1A
<iframe src="https://docs.google.com/presentation/d/1HQGHgFrZCr8yWmbz0R7lxYGiZpR_Xu_2/preview" width="640" height="480" allow="autoplay"></iframe>  

### 1B
<iframe src="https://docs.google.com/presentation/d/1U1PHHxf_9nJbht6ZWAm9-XpDARuTRPD5/preview" width="640" height="480" allow="autoplay"></iframe>  



## Lab 1A
### Variables
Create 2 numeric variables and assign values for each

```{r}
x = 10
y = 6
```

Calculate the sum of them

```{r}
total = x + y
total
```

Calculate the square root of the total
```{r}
sr = sqrt(total)
sr
```


### Data Structures 
Vector
```{r}
v <- c(1,2,3,4)
v
```


Matrix
```{r}
m <- matrix(1:6, nrow = 2)
m
```


Dataframe
```{r}
df <- data.frame(age=c(25,30), name=c("Mo","Tom"), group=c("A", "B"))
df
```

List
```{r}
lst <- list(numbers=v, info=df)
lst
```


### Install BioconductoR packages
```{r, eval=FALSE}
install.packages("BiocManager")
library(BiocManager)
BiocManager::install("ALL")
library("ALL")
data(ALL)
```

