# Module 2

## Lecture


<!--<iframe width="640" height="360" src="YOUTUBE EMBED LINK" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>-->

### 2A
<iframe src="https://docs.google.com/presentation/d/1PzqDljdBka-mxb7osNcveBCvpzLRsKTS/preview" width="640" height="480" allow="autoplay"></iframe>  

### 2B
<iframe src="https://docs.google.com/presentation/d/1Dd5Dow29sairtG8tTLhsYChQV3qZGc5o/preview" width="640" height="480" allow="autoplay"></iframe>  


## Lab 2A Tasks

```{r, eval=FALSE, message=FALSE}
# Task 1 – Basic Filtering
# Use a for loop with if/else conditions
# Go through each row of the dataset and:
# Print a message if the patient has High BP (> 140) # Tip: use the paste function, 
# Print a message if the patient has Low BP (< 90)
# Otherwise, mark them as Normal

# read data
bp_data <- read.csv2("Desktop/R/data/BloodPressure_wDates.csv", sep = ",")

# Use for loop
for (i in 1:nrow(bp_data)) {
  if (bp_data$BloodPressure[i] > 140) {
    print(paste("Patient", bp_data$ID[i], "has HIGH blood pressure"))
  } else if (bp_data$BloodPressure[i] < 90) {
    print(paste("Patient", bp_data$ID[i], "has LOW blood pressure"))
  } else {
    print(paste("Patient", bp_data$ID[i], "is NORMAL"))
  }
}


# Use apply() instead of loops
bp_data$BP_Status <- apply(bp_data, 1, function(row) {
  if (as.numeric(row["BloodPressure"]) > 140) {
    "HIGH"
  } else if (as.numeric(row["BloodPressure"]) < 90) {
    "LOW"
  } else {
    "NORMAL"
  }
})
```



## Lab 2A
### Read data in to R
### read CSV - base functions

```{r, eval=FALSE, message=FALSE}
bp <- read.csv2("Desktop/R/data/BloodPressure_Data.csv") # no sepqration
# take a quick look at the data
head(bp)
```

```{r, eval=FALSE, message=FALSE}
bp <- read.csv2("Desktop/R/data/BloodPressure_Data.csv", sep = ",") # no sepqration
# take another look at the data
head(bp)
str(bp)
```

```{r, eval=FALSE, message=FALSE}
# readr functions
library(readr)
```

```{r, eval=FALSE, message=FALSE}
# Read the CSV file
bp_data <- read_csv("Desktop/R/data/BloodPressure_Data.csv")
```

```{r, eval=FALSE, message=FALSE}
# Take a quick look at the data
head(bp_data)
str(bp_data)
```

```{r, eval=FALSE, message=FALSE}
# Work with date
library(readr)
library("lubridate")
```

```{r, eval=FALSE, message=FALSE}
# read ALL data
bp <-  read.csv2("Desktop/R/data/BloodPressure_wDates.csv", sep = ",")
```

```{r, eval=FALSE, message=FALSE}
# Convert date column and extract year
bp$Date <- ymd(bp$Date)
bp$Year <- year(bp$Date)
```

```{r, eval=FALSE, message=FALSE}
# Filtering blood pressure patients by year and gender
subset(bp, Year == 2003 & Gender == "f")
```

### Conditions and loops

```{r, eval=FALSE, message=FALSE}
# If {} else {} statement 
if (condition) {
  # code if TRUE
} else {
  # code if FALSE
}
```

```{r, eval=FALSE, message=FALSE}
# If else example
age <- 55
if (age > 50) {
  print("Older patient")
} else {
  print("Younger patient")
}
```

```{r, eval=FALSE, message=FALSE}
# If {} else if {} else statement 

if (condition1) {
  # code if condition1 is TRUE
} else if (condition2) {
  # code if condition2 is TRUE
} else {
  # code if none are TRUE
}
```

```{r, eval=FALSE, message=FALSE}
# If else if example
age <- 35

if (age < 18) {
  print("Child")
} else if (age >= 18 & age < 60) {
  print("Adult")
} else {
  print("Senior")
}
```

```{r, eval=FALSE, message=FALSE}
# for loops
for (i in 1:5) {
  print(i)
}
```

```{r, eval=FALSE, message=FALSE}
# for loop example
patients <- c("P1", "P2", "P3")
for (p in patients) {
  print(paste("Processing:", p))
}
```

```{r, eval=FALSE, message=FALSE}
# the apply () family vs. loops
# Using a for loop
m <- matrix(1:9, nrow=3)
row_sums <- c()
for (i in 1:nrow(m)) {
  row_sums[i] <- sum(m[i, ])
}
```

```{r, eval=FALSE, message=FALSE}
# Using apply()
row_sums2 <- apply(m, 1, sum)
```

```{r, eval=FALSE, message=FALSE}
# the apply() family
# apply()
apply(m, 1, sum)   # row sums
apply(m, 2, mean)  # column means
```

```{r, eval=FALSE, message=FALSE}
# lapply()
lapply(list(1:3, 4:6), mean)
```

```{r, eval=FALSE, message=FALSE}
# sapply()
sapply(list(1:3, 4:6), mean)
```

```{r, eval=FALSE, message=FALSE}
# lapply()
lapply(list(1:3, 4:6), mean)
```

```{r, eval=FALSE, message=FALSE}
# tapply()
ages <- c(21, 25, 30, 40, 35)
gender <- c("M", "M", "F", "F", "M")
tapply(ages, gender, mean)   # mean age by gender
```

```{r, eval=FALSE, message=FALSE}
# mapply()
nums1 <- 1:5
nums2 <- 6:10
mapply(sum, nums1, nums2)   # adds 1+6, 2+7, … 5+10
```



























